version: "3.8"
services:
  mysqldb:
    image: mysql
    env_file: ./backend/.env
    environment:
      - MYSQL_DATABASE= $DB_NAME
      - MYSQL_ROOT_PASSWORD= $DB_PASSWORD
    ports:
      - $DB_PORT:$DB_PORT

  app:
    build: .
    depends_on:
      - mysqldb
    links:
      - mysqldb
    ports:
      - 3000:3000
